data_dir: 'data/'
model:
  name: 'specter'
  path: '../model.onnx'
  inputs:
    input_ids: True
    attention_mask: True
    token_type_ids: True
tokenizer:
  pretrained_model: 'sentence-transformers/all-mpnet-base-v2'
  max_length: 512
