mlflow:
  tracking_uri: 'file:mlruns' # Can be remote server as well eg https://my-tracking-server:5000
  experiment_name: 'Scidocs'
  run_name: 'reproduced-fp32'
embeddings_path: 'data/reproduced-specter-fp32'
results_file: 'results/reproduced-specter-results.txt'
